### PR TITLE
Fix: GraphQL codegen / `cargo run` in rust project

### LINKED ISSUE #155: rindexer codegen graphql failure
Using no-code project, with postgres docker running, and "rindexer start graphql" running in another terminal.
Graphql is definitely working otherwise, as localhost:3001/playground is working.

```
$ rindexer codegen graphql
Failed to generate graphql queries: Network request failed: error decoding response body: expected value at line 1 column 1
Error: Network(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })
```

### PR DESCRIPTION
**Pull request by desfero**
Fixes #155

### CODE REVIEW

File: cli/src/commands/codegen.rs [hunk 1]
```diff
@@ -1,26 +1,27 @@
...
-    rindexer_yaml::validate_rindexer_yaml_exist,
-};
-
 pub async fn handle_codegen_command(
     project_path: PathBuf,
     subcommand: &CodegenSubcommands,
 ) -> Result<(), Box<dyn std::error::Error>> {
     if let CodegenSubcommands::GraphQL { endpoint } = subcommand {
-        let url = endpoint.as_deref().unwrap_or("http://localhost:3001");
+        let default_url = format!("http://localhost:{}/graphql", default_graphql_port());
```
Comment (desfero) [inline cli/src/commands/codegen.rs:23]: `/graphql` was missing

File: core/src/api/generate_schema.rs [hunk 2]
```diff
@@ -1,24 +1,20 @@
...
 
-use crate::api::generate_operations::{generate_operations, GenerateOperationsError};
-
 #[derive(thiserror::Error, Debug)]
 pub enum GenerateGraphqlQueriesError {
     #[error("Network request failed: {0}")]
     Network(#[from] reqwest::Error),
 
-    #[error("Failed to parse JSON: {0}")]
-    JsonParse(#[from] serde_json::Error),
```
Comment (desfero) [inline core/src/api/generate_schema.rs:14]: not used

File: core/src/generator/build.rs [hunk 3]
```diff
@@ -530,7 +530,7 @@ serde = {{ version = "1.0", features = ["derive"] }}
                 let mut port: Option<u16> = None;
 
                 let args = args.iter();
-                if args.len() == 0 {
+                if args.len() == 1 {
```
Comment (desfero) [inline core/src/generator/build.rs:533]: it will always contain at least one element, first one is path to  the executable
